name: Keet Automation

inputs:
  GITHUB_TOKEN:
    type: string
    description: "from secrets.GITHUB"
    required: true
  seed:
    type: string
    description: "seed for the automation"
    required: true
  remote:
    type: string
    description: "remote key for the automation"
    required: true
  job:
    type: string
    description: "job to run"
    required: true
  commit:
    type: string
    description: "commit"
    required: false
  channel:
    type: string
    description: "channel"
    required: false
  dir:
    type: string
    description: "dir"
    required: false
  artifact:
    type: string
    description: "artifact to download"
    required: false
  skip-install:
    type: string
    description: "skip install step"
    required: false
  notify:
    type: string
    description: 'notify'
    required: false
    default: 'true'
  dry-run:
    type: string
    description: 'dry run'
    required: false

runs:
  using: composite
  steps:
    - name: Install keet-automation
      env:
        NODE_AUTH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      run: |
        npm install -g @holepunchto/keet-automation

    - name: Build
      env:
        COMMIT: ${{ inputs.commit }}
        CHANNEL: ${{ inputs.channel }}
        DIR: ${{ inputs.dir }}
        ARTIFACT: ${{ inputs.artifact }}
        SEED: ${{ inputs.seed }}
        REMOTE: ${{ inputs.remote }}
        JOB: ${{ inputs.job }}
        SKIP_INSTALL_FLAG: ${{ inputs.skip-install == 'true' && '--skip-install' || '' }}
        NOTIFY: ${{ inputs.notify == 'true' && '--notify true' || '' }}
        DRY_RUN: ${{ inputs.dry-run == 'true' && '--dry-run' || '' }}
      shell: bash
      run: |
        COMMIT_ARG=""
        if [ -n "$COMMIT" ]; then
          COMMIT_ARG="--commit $COMMIT"
        fi
        CHANNEL_ARG=""
        if [ -n "$CHANNEL" ]; then
          CHANNEL_ARG="--channel $CHANNEL"
        fi
        DIR_ARG=""
        if [ -n "$DIR" ]; then
          DIR_ARG="--dir $DIR"
        fi
        if [ -n "$ARTIFACT" ]; then
          ARTIFACT_ARG="--artifact $ARTIFACT"
        fi

        keet-automation \
          --seed $SEED \
          --remote $REMOTE \
          $JOB \
          $COMMIT_ARG \
          $CHANNEL_ARG \
          $DIR_ARG \
          $ARTIFACT_ARG \
          $SKIP_INSTALL_FLAG \
          $NOTIFY \
          $DRY_RUN \
