name: Create release
description: Create a GitHub release

inputs:
  workspaces:
    description: Pack all workspace packages
    default: false
  include-workspace-root:
    description: Also pack the workspace root
    default: false

runs:
  using: composite
  steps:
    - run: npm pack ${{ inputs.workspaces == 'true' && '--workspaces' || '' }} ${{ inputs.include-workspace-root == 'true' && '--include-workspace-root' || '' }}
      shell: bash
    - id: pack
      run: echo "packages=$(ls *.tgz)" >> "$GITHUB_OUTPUT"
      shell: bash
    - run: gh release create ${{ github.ref_name }} ${{ steps.pack.outputs.packages }} --generate-notes
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
