name: Setup Repo

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Git config
      shell: bash
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email 'bot@github.actions.com'
