name: Trigger Canary

on:
  workflow_call:
    inputs:
      repository_name:
        description: "Name of the repository triggering canary tests"
        required: true
        type: string
      ref_name:
        description: "Git ref name (tag or branch)"
        required: true
        type: string
    secrets:
      canary_dispatch_pat:
        description: "PAT for triggering canary tests"
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger canary tests
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.canary_dispatch_pat }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/holepunchto/canary-tests/dispatches \
          -d '{"event_type":"triggered-by-${{ inputs.repository_name }}-${{ inputs.ref_name }}"}'
