name: Download prebuilds
description: Download native prebuilds

inputs:
  prefix:
    description: The prebuild prefix
    default: prebuilds

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@9000827ccba6bdab643e8b6fd33ac0654aef8333 #v8.0.2
      with:
        path: ${{ inputs.prefix }}
        merge-multiple: true
