name: Pear base
description: Configure a Pear project

runs:
  using: composite
  steps:
    - uses: holepunchto/actions/node-base@v1

    - name: Setup Pear
      run: npx -y pear
      shell: bash

    - name: Add Pear to $PATH
      run: |
        case "$RUNNER_OS" in
          Linux)   echo "$HOME/.config/pear/bin" >> "$GITHUB_PATH" ;;
          macOS)   echo "$HOME/Library/Application Support/pear/bin" >> "$GITHUB_PATH" ;;
          Windows) echo "$USERPROFILE\\AppData\\Roaming\\pear\\bin" >> "$GITHUB_PATH" ;;
        esac
      shell: bash
