name: Checkout
description: Checkout a git repository

inputs:
  fetch-depth:
    description: Number of commits to fetch. 0 indicates all history for all branches and tags
    default: '1'

runs:
  using: composite
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
        fetch-depth: ${{ inputs.fetch-depth }}
