name: Publish
description: Publish to npm (alias for publish-npm)

inputs:
  tag:
    description: npm dist-tag to publish under
    default: latest
  ref-name:
    description: Git tag and GitHub release name. Defaults to github.ref_name.
    required: false
  workspaces:
    description: Publish all workspace packages
    default: false
  include-workspace-root:
    description: Also publish the workspace root
    default: false
  node-auth-token:
    description: npm auth token

runs:
  using: composite
  steps:
    - uses: holepunchto/actions/publish-npm@v1
      with:
        tag: ${{ inputs.tag }}
        ref-name: ${{ inputs.ref-name }}
        workspaces: ${{ inputs.workspaces }}
        include-workspace-root: ${{ inputs.include-workspace-root }}
        node-auth-token: ${{ inputs.node-auth-token || env.NODE_AUTH_TOKEN }}
