name: Publish
description: Create a GitHub release and publish to npm

runs:
  using: composite
  steps:
    - run: npm publish --ignore-scripts
      shell: bash
    - uses: holepunchto/actions/create-release@v1
