name: Publish
description: Create a GitHub release and publish to npm

inputs:
  workspaces:
    description: Publish all workspace packages
    default: false
  include-workspace-root:
    description: Also publish the workspace root
    default: false

runs:
  using: composite
  steps:
    - run: npm publish --ignore-scripts ${{ inputs.workspaces == 'true' && '--workspaces' || '' }} ${{ inputs.include-workspace-root == 'true' && '--include-workspace-root' || '' }}
      shell: bash
    - uses: holepunchto/actions/create-release@v1
