name: Setup Socket.dev
description: Install and configure Socket.dev

runs:
  using: composite
  steps:
    - uses: socketdev/action@48bdbd2f664f69025e9cf90b34394d549c1e7c9e
      with:
        mode: firewall
        job-summary: errors
