name: Bump Deps

inputs:
  use-create-pr:
    type: boolean
    description: "create a PR"
    default: false
  GITHUB_TOKEN:
    type: string
    description: "from secrets.GITHUB"
    required: true
  labels:
    type: string
    description: "labels for the PR"
    default: ""
  update-package-json:
    type: boolean
    description: "update package.json"
    default: false

outputs:
  pull-request-url:
    value: ${{ steps.pr.outputs.pull-request-url }}

runs:
  using: composite
  steps:
    - name: Bump deps
      env:
        NODE_AUTH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      run: |
        if [[ "${{ inputs.update-package-json }}" == "true" ]]; then
          npx npm-check-updates -t semver -u
        fi
        rm package-lock.json
        npm install

    - if: ${{ inputs.use-create-pr == 'true' }}
      name: Create PR
      id: pr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        draft: always-true # require user to manually click "ready for review" for triggering another workflow, ref. https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
        commit-message: Bump deps
        committer: GitHub Actions Bot <noreply@holepunchto.com>
        author: GitHub Actions Bot <noreply@holepunchto.com>
        branch: bump-deps
        labels: ${{ inputs.labels }}
        title: "Bump deps"
        body: |
          Bump all deps
