name: Setup NASM
description: Install and configure NASM

runs:
  using: composite
  steps:
    - run: sudo apt install -y nasm
      if: ${{ runner.os == 'Linux' }}
      shell: bash
    - run: brew install nasm
      if: ${{ runner.os == 'macOS' }}
      shell: bash
    - run: choco install nasm
      if: ${{ runner.os == 'Windows' }}
      shell: bash
