name: Build Pear
description: Check out and build Pear from source, installing it onto PATH

inputs:
  ref:
    description: The `holepunchto/pear` git ref (branch, tag, or SHA) to compile
  path:
    description: The directory to check out and build the Pear source in
    default: .pear

runs:
  using: composite
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        repository: holepunchto/pear
        ref: ${{ inputs.ref }}
        path: ${{ inputs.path }}
        persist-credentials: false
    - name: 'Install dependencies (Linux/macOS)'
      if: ${{ runner.os != 'Windows' }}
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      run: |
        npm ci --ignore-scripts
      working-directory: ${{ inputs.path }}
      shell: bash
    - name: 'Install dependencies (Windows)'
      if: ${{ runner.os == 'Windows' }}
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      run: |
        npm ci --ignore-scripts
      working-directory: ${{ inputs.path }}
      shell: pwsh
    - name: 'Build (Linux/macOS)'
      if: ${{ runner.os != 'Windows' }}
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      run: |
        npm run make
      working-directory: ${{ inputs.path }}
      shell: bash
    - name: 'Build (Windows)'
      if: ${{ runner.os == 'Windows' }}
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      run: |
        npm run make
      working-directory: ${{ inputs.path }}
      shell: pwsh
    - id: prefix-bash
      if: ${{ runner.os != 'Windows' }}
      run: echo "path=$(npm prefix --global)" >> "$GITHUB_OUTPUT"
      shell: bash
    - id: prefix-pwsh
      if: ${{ runner.os == 'Windows' }}
      run: Add-Content $env:GITHUB_OUTPUT "path=$(npm prefix --global)"
      shell: pwsh
    - run: cp out/make/pear "$PREFIX/bin"
      if: ${{ runner.os != 'Windows' }}
      env:
        PREFIX: ${{ steps.prefix-bash.outputs.path }}
      working-directory: ${{ inputs.path }}
      shell: bash
    - run: Copy-Item out/make/pear.exe "$env:PREFIX/"
      if: ${{ runner.os == 'Windows' }}
      env:
        PREFIX: ${{ steps.prefix-pwsh.outputs.path }}
      working-directory: ${{ inputs.path }}
      shell: pwsh
