name: Build Bare
description: Check out and build Pear from source, installing it onto PATH

inputs:
  ref:
    description: The `holepunchto/pear` git ref (branch, tag, or SHA) to compile
  path:
    description: The directory to check out and build the Pear source in
    default: .pear

runs:
  using: composite
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        repository: holepunchto/pear
        ref: ${{ inputs.ref }}
        path: ${{ inputs.path }}
        persist-credentials: false
    # TODO: Use node-base action
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: 20
        registry-url: 'https://npm.pkg.github.com'
    - name: 'Install dependencies (Linux/macOS)'
      if: ${{ runner.os != 'Windows' }}
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      run: |
        npm ci --ignore-scripts
      working-directory: ${{ inputs.path }}
      shell: bash
    - name: 'Install dependencies (Windows)'
      if: ${{ runner.os == 'Windows' }}
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      run: |
        npm ci --ignore-scripts
      working-directory: ${{ inputs.path }}
      shell: pwsh
    - name: 'Build (Linux/macOS)'
      if: ${{ runner.os != 'Windows' }}
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      run: |
        npm run make
      working-directory: ${{ inputs.path }}
      shell: bash
    - name: 'Build (Windows)'
      if: ${{ runner.os == 'Windows' }}
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      run: |
        npm run make
      working-directory: ${{ inputs.path }}
      shell: pwsh
    - name: 'Install (Linux/macOS)'
      if: ${{ runner.os != 'Windows' }}
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      run: |
        npm i -g .
      working-directory: ${{ inputs.path }}
      shell: bash
    - name: 'Install (Windows)'
      if: ${{ runner.os == 'Windows' }}
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      run: |
        npm i -g .
      working-directory: ${{ inputs.path }}
      shell: pwsh
