name: Setup
description: Node LTS + fixed action versions

runs:
  using: composite
  steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with: { node-version: lts/* }
    - run: npm install
      shell: bash
