name: Bump Deps

on:
  workflow_call:
    inputs:
      labels:
        type: string
        description: "labels for the PR"
        default: ''
      update-package-json:
        type: boolean
        description: "update package.json"
        default: true
    outputs:
      pull-request-url:
        value: ${{ jobs.bump-deps.outputs.pull-request-url }}

jobs:
  bump-deps:
    runs-on: ubuntu-latest
    outputs:
      pull-request-url: ${{ steps.bump-deps.outputs.pull-request-url }}
    steps:
      - name: Setup repo
        uses: holepunchto/actions/.github/steps/setup-repo@v1

      - name: Bump Deps
        id: bump-deps
        uses: holepunchto/actions/.github/steps/bump-deps@v1
        with:
          use-create-pr: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ inputs.labels }}
          update-package-json: ${{ inputs.update-package-json }}
