name: Bump Versions

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: 'version type: prerelease, patch, minor, major'
        required: true
      labels:
        type: string
        description: 'labels for the PR'
        default: ''
    outputs:
      pull-request-url:
        value: ${{ jobs.bump-versions.outputs.pull-request-url }}

jobs:
  bump-versions:
    runs-on: ubuntu-latest
    outputs:
      pull-request-url: ${{ steps.bump-versions.outputs.pull-request-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git config
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'bot@github.actions.com'

      - name: Bump Versions
        id: bump-versions
        uses: holepunchto/actions/.github/steps/bump-versions@v1
        with:
          use-create-pr: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
          labels: ${{ inputs.labels }}
