name: Bump Version

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: 'version type: prerelease, patch, minor, major'
        required: true
      labels:
        type: string
        description: 'labels for the PR'
        default: ''
      channel-id:
        type: string
        description: "channel to notify Slack"
        required: false
    outputs:
      version: 
        value: ${{ jobs.bump-version.outputs.version }}
      pull-request-url:
        value: ${{ jobs.bump-version.outputs.pull-request-url }}

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump-version.outputs.version }}
      pull-request-url: ${{ steps.bump-version.outputs.pull-request-url }}
    steps:
      - name: Setup repo
        uses: holepunchto/actions/.github/steps/setup-repo@v1

      - name: Bump Version
        id: bump-version
        uses: holepunchto/actions/.github/steps/bump-version@v1
        with:
          use-create-pr: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
          labels: ${{ inputs.labels }}

      - name: Notify Slack
        if: ${{ inputs.channel-id }}
        uses: holepunchto/actions/.github/steps/notify-slack@v1
        with:
          auth_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ inputs.channel-id }}
          message: "Please review: Bump Version ${{ steps.bump-version.outputs.pull-request-url }}"
