name: Bump Deps

on:
  workflow_call:
    inputs:
      labels:
        type: string
        default: ''
    outputs:
      pull-request-url:
        value: ${{ jobs.bump-deps.outputs.pull-request-url }}
jobs:
  bump-deps:
    runs-on: ubuntu-latest
    outputs:
      pull-request-url: ${{ steps.bump-deps.outputs.pull-request-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git config
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'bot@github.actions.com'

      - name: Bump Deps
        id: bump-deps
        uses: holepunchto/actions/.github/steps/bump-deps@v1
        with:
          use-create-pr: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
