name: Bump Versions

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
    outputs:
      pull-request-url:
        value: ${{ jobs.bump-versions.outputs.pull-request-url }}

jobs:
  bump-versions:
    runs-on: ubuntu-latest
    outputs:
      pull-request-url: ${{ steps.bump-versions.outputs.pull-request-url }}
    steps:
      - name: Bump Versions
        id: bump-versions
        # TODO: Use @main after merging https://github.com/holepunchto/actions/pull/1
        uses: holepunchto/actions/.github/steps/bump-versions@87f1c8e3ef71f8659b08a4dbed0e28b3068aad3f
        with:
          use-checkout: true
          use-git-config: true
          use-create-pr: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
