name: Bump Versions

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
    outputs:
      pull-request-url:
        value: ${{ jobs.bump-versions.outputs.pull-request-url }}

jobs:
  bump-versions:
    runs-on: ubuntu-latest
    outputs:
      pull-request-url: ${{ steps.bump-versions.outputs.pull-request-url }}
    steps:
      - name: Bump Versions
        id: bump-versions
        uses: ./.github/steps/bump-versions
        with:
          use-checkout: true
          use-git-config: true
          use-create-pr: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
