name: Bump Deps

on:
  workflow_call:
    inputs:
      labels:
        type: string
        description: "labels for the PR"
        default: ''
      channel-id:
        type: string
        description: "channel to notify Slack"
        required: false
    outputs:
      pull-request-url:
        value: ${{ jobs.bump-deps.outputs.pull-request-url }}

jobs:
  bump-deps:
    runs-on: ubuntu-latest
    outputs:
      pull-request-url: ${{ steps.bump-deps.outputs.pull-request-url }}
    steps:
      - name: Setup repo
        uses: holepunchto/actions/.github/steps/setup-repo@v1

      - name: Bump Deps
        id: bump-deps
        uses: holepunchto/actions/.github/steps/bump-deps@v1
        with:
          use-create-pr: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ inputs.labels }}

      - name: Notify Slack
        if: ${{ inputs.channel-id }}
        uses: holepunchto/actions/.github/steps/notify-slack@v1
        with:
          auth_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ inputs.channel-id }}
          message: "Please review: Bump Deps ${{ steps.bump-deps.outputs.pull-request-url }}"
