name: Bump Deps v2

on:
  workflow_call:
    inputs:
      labels:
        type: string
        default: ""
    outputs:
      pull-request-url:
        value: ${{ jobs.bump-deps.outputs.pull-request-url }}

jobs:
  bump-deps:
    runs-on: ubuntu-latest
    outputs:
      pull-request-url: ${{ steps.bump-deps.outputs.pull-request-url }}
    steps:
      - name: Bump Deps
        id: bump-deps
        # TODO: Use @main after merging https://github.com/holepunchto/actions/pull/1
        uses: holepunchto/actions/.github/steps/bump-deps@87f1c8e3ef71f8659b08a4dbed0e28b3068aad3f
        with:
          use-checkout: true
          use-git-config: true
          use-create-pr: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
